# Generated by Django 5.2.11 on 2026-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('user', 'test')},
        ),
    ]
