# Generated by Django 5.2.11 on 2026-03-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lessoncategory_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='questions/videos/'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='options/videos/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='words/videos/'),
        ),
    ]
