# Generated by Django 5.2.11 on 2026-03-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lesson_video_url_alter_question_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(),
        ),
    ]
